name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: live

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Build for production
      run: |
        npm ci
        npx tailwindcss -i ./src/css/input.css -o ./src/css/dist/output.css --minify

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@164a3e861eade8146ae8bd738d66b107e70ad6cf
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ARGS: "-raL --delete"
        SOURCE: "src/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_DEPLOY_PATH }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
